# Generated by Django 2.1 on 2020-08-17 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 8, 17, 10, 17, 33, 793120, tzinfo=utc)),
        ),
    ]
